name: tag and publish crate [manual]

on:
  workflow_dispatch:
    inputs:
      tag-increment:
        default: patch
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: macos-latest
